# configuration for spring boot application
spring.application.name=homelab-cloud-backend

# url of the database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/homelab_db}

# username of the database
spring.datasource.username=${DB_USERNAME:homelab_user}

# password of the database
spring.datasource.password=${DB_PASSWORD:admin}

#driver for the database
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================================================
# configuration for hibernate / jpa

# update the database schema automatically
spring.jpa.hibernate.ddl-auto=update

# the sql statements will be printed to the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# configuration the flyway database migration tool
spring.flyway.enabled=false
# activate the flyway database migration tool

# ==========================================
# 4. LIMITES PARA TU DRIVE (SUBIDA DE ARCHIVOS)
# ==========================================
# Por defecto Spring limita a 1MB. Para un drive personal, vamos a subirlo (ejemplo 50MB)
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# ==========================================
# 5. CONFIGURACION JWT
# ==========================================
# Una clave secreta MUY larga (debe ser de al menos 256 bits / 32 caracteres)
jwt.secret=${JWT_SECRET:mi_super_secreto_muy_largo_y_seguro_para_desarrollo_homelab_2026}

# Tiempo de expiracion del token en milisegundos (Ejemplo: 24 horas = 86400000 ms)
jwt.expiration=${JWT_EXPIRATION:86400000}


homelab.storage.avatar-dir=${user.home}/homelab-cloud/avatars
homelab.storage.files-dir=${user.home}/homelab-cloud/files
